# Generated by Django 4.0.2 on 2022-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
